apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
  labels:
    app: es-cluster
spec:
  serviceName: es-cluster
  replicas: 1
  selector:
    matchLabels:
      app: es-cluster
  template:
    metadata:
      labels:
        app: es-cluster
    spec:
      serviceAccountName: elastic
      containers:
      - name: es-cluster
        image: elasticsearch:8.5.1
        securityContext:
          privileged: true
        resources:
            limits:
              memory: "2Gi"
              cpu: 1000m
            requests:
              cpu: 400m
              memory: "1500Mi"
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 5
        ports:
        - containerPort: 9200
          name: req
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        env:
          - name: cluster.name
            value: es-cluster-ocp
          - name: node.name              #get node name from metadata of pods.
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.type
            value: "single-node"
          - name: ES_JAVA_OPTS
            value: "-Xms1024m -Xmx1024m"
          - name: xpack.security.enabled
            value: "false"
          - name: bootstrap.memory_lock
            value: "false"
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: es-cluster
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: es-cluster
spec:
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
  selector:
    app: es-cluster
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: elasticsearch-route
  labels:
    app: es-cluster
spec:
  to:
    kind: Service
    name: elasticsearch  # This should match the name of your service
  port:
    targetPort: 9200
  tls:
    termination: edge
  host: elastic.apps-crc.testing

