host: god.example.com

imagePullSecrets: regcred

image:
  repository: build-dashboard
  tag: latest
  pullPolicy: Always

ingress:
  enabled: false

route:
  enabled: true

config:
  projectDirectory: /projects
  uploadDirectory: /upload
  teamsWebhookUrl: https://xxx
