# create deployment for the application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: build-dashboard
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/cm.yaml") . | sha256sum }}
      labels:
        app: build-dashboard
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
    {{- end }}
      containers:
        - name: build-dashboard
          env:
            - name: CONFIG_FILE
              value: /config/config.yaml
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: build-dashboard
              mountPath: /projects
            - name: build-config
              mountPath: /config/config.yaml
              subPath: config.yaml
            - name: build-upload
              mountPath: /upload
      volumes:
        - configMap:
            name: build-config
            items:
            - key: config.yaml
              path: config.yaml
          name: build-config
        - name: build-dashboard
          persistentVolumeClaim:
            claimName: build-dashboard-pvc
        - name: build-upload
          emptyDir: {}