# service
apiVersion: v1
kind: Service
metadata:
  name: build-dashboard
spec:
  selector:
    app: build-dashboard
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
