replicaCount: 1

image:
  repository: grafana/grafana
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1000m"

adminPassword: strongpassword # Consider using a secret for this in production

route:
  enabled: true
  host: grafana.apps-crc.testing
  tls:
    enabled: true
    termination: edge
