apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: es-cluster
spec:
  type: {{ .Values.service.type }}
  ports:
{{ toYaml .Values.service.ports | indent 4 }}
  selector:
    app: es-cluster
