apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
  labels:
    app: es-cluster
spec:
  serviceName: es-cluster
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: es-cluster
  template:
    metadata:
      labels:
        app: es-cluster
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: es-cluster
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        securityContext:
          privileged: true
        resources:
{{ toYaml .Values.resources | indent 10 }}
        readinessProbe:
{{ toYaml .Values.probes.readinessProbe | indent 10 }}
        ports:
{{ toYaml .Values.ports | indent 8 }}
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        env:
{{ toYaml .Values.env | indent 10 }}
      initContainers:
{{ toYaml .Values.initContainers | indent 8 }}
  volumeClaimTemplates:
{{ toYaml .Values.volumeClaimTemplates | indent 4 }}
